name: ğŸ˜¡ [DEPLOY] Pull Request actions

on:
  pull_request:
    types: [labeled, unlabeled, synchronize, opened]

jobs:
  alpha_deploy:
    if: contains(github.event.pull_request.labels.*.name, 'alpha')
    runs-on: ubuntu-latest
    name: Deploy to Alpha
    steps:
      - name: ğŸ Checkout Repository
        uses: actions/checkout@v4

      - name: ğŸ“¦ Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://npm.pkg.github.com/'

      - name: ğŸ”— Prepare Corepack
        run: |
          corepack prepare pnpm@10 --activate

      - name: ğŸ”— Resolve Dependency
        # Todo: caching pnpm store
        run: |
          corepack enable
          pnpm install --frozen-lockfile

      - name: ğŸ›« Build application
        id: build_output
        run: pnpm build

      - name: ğŸš€ Deploy to CloudFlare
        id: deploy_to_cloudflare
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: 'soongpt-web-alpha'
          directory: 'dist'
          branch: ${{ github.head_ref || github.ref_name }}
          wranglerVersion: '3'
